### ISSUE TITLE
16.9 (535.230.02) fails to build on 6.14.11-5-pve for Tesla M60 GPU

### ISSUE THREAD

**Issue by nate-moo** [anomixer/proxmox-vgpu-installer#18]
Hello friends, I've looked through the issues and tried to find a solution but could not figure out why the driver fails to build. I am attaching the debug.log, SR-IOV and IOMMU are enabled. I tried also using 17.6 for the hell of it and that one successfully built but the driver won't bind bc my GPU isn't supported. I also tried 16.8 and 16.7 but those gave errors related to building with the wrong toolchain, for some reason they were selecting clang instead of gcc despite having both installed on the machine.

[nvidia-installer.log](https://github.com/user-attachments/files/25615862/nvidia-installer.log)
[iommu.log](https://github.com/user-attachments/files/25615861/iommu.log) - iommu group, pci id, name, etc.
[debug.log](https://github.com/user-attachments/files/25615860/debug.log)

if it helps the system is a Dell EMC VxRail V570F (Poweredge R740XD equivalent), the M60 came stock with the system to my knowledge

```
root@biggastinka:~/proxmox-vgpu-installer# bash proxmox-installer.sh 
[...]
Welcome to the Nvidia vGPU installer version 1.75 for Proxmox
This system is running Proxmox version 9.1.6 with kernel 6.14.11-5-pve

You are currently at step 2 of the installation process

Proceeding with the installation

[+] Intel IOMMU Enabled
[-] You are running Proxmox version 9.1.6
[-] Review GPU database output for the recommended branch.

Select vGPU driver version:

1: 19.3 (580.105.06) [Native GPUs only (Select this for most situations.)]
2: 19.2 (580.95.02) [Native GPUs only (no patch file available)]
3: 19.1 (580.82.02) [Native GPUs only (no patch file available)]
4: 19.0 (580.65.05) [Native GPUs only]
5: 18.4 (570.172.07) [Native GPUs only]
6: 18.3 (570.158.02) [Native GPUs only]
7: 18.2 (570.148.06) [Native GPUs only]
8: 18.1 (570.133.10) [Native GPUs only]
9: 18.0 (570.124.03) [Native GPUs only]
10: 17.6 (550.163.02) [Native GPUs only]
11: 17.5 (550.144.02) [Turing GPUs (Select this for most situations.)]
12: 17.4 (550.127.06) [Turing GPUs]
13: 17.3 (550.90.05) [Turing GPUs]
14: 17.1 (550.54.16) [Turing GPUs]
15: 17.0 (550.54.10) [Turing GPUs]
16: 16.9 (535.230.02) [Pascal or older GPUs (Select this for most situations.)]
17: 16.8 (535.216.01) [Pascal or older GPUs]
18: 16.7 (535.183.04) [Pascal or older GPUs]
19: 16.5 (535.161.05) [Pascal or older GPUs]
20: 16.4 (535.161.05) [Pascal or older GPUs]
21: 16.3 (535.154.02) [Pascal or older GPUs]
22: 16.2 (535.129.03) [Pascal or older GPUs]
23: 16.1 (535.104.06) [Pascal or older GPUs]
24: 16.0 (535.54.06) [Pascal or older GPUs]

Enter your choice: 16
[-] Driver version: NVIDIA-Linux-x86_64-535.230.02-vgpu-kvm.run
[+] Driver file NVIDIA-Linux-x86_64-535.230.02-vgpu-kvm.run already exists and MD5 checksum matches. Skipping download.
[+] MD5 checksum matched. Downloaded file is valid.
Installing native driver info ./NVIDIA-Linux-x86_64-535.230.02-vgpu-kvm.run --dkms -m=kernel -s
[+] Installing native driver
[!] Command failed: Installing native driver (see /root/proxmox-vgpu-installer/debug.log)
root@biggastinka:~/proxmox-vgpu-installer#
```

I noticed a few errors (and lots of warnings) in the build logs:
```
nvidia-vgpu-vfio/nvidia-vgpu-vfio.c:6014:18: error: expected ',' or ';' before 'IOMMUFD'
 6014 | MODULE_IMPORT_NS(IOMMUFD);
      |                  ^~~~~~~
```
```
nvidia-vgpu-vfio/nvidia-vgpu-vfio.c:4921:18: error: 'no_llseek' undeclared here (not in a function); did you mean 'noop_llseek'?
 4921 |        .llseek = no_llseek,
      |                  ^~~~~~~~~
      |                  noop_llseek
```

**Comment by tdtmusic2** [comment]
Hello. I have a similar issue at the same step, with a Tesla T4, driver cannot be installed. In the log a bunch of errors like these:

```
nvidia/nv-acpi.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-acpi.o] Error 1
nvidia/nv-cray.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-cray.o] Error 1
  CC [M]  nvidia/nv-mmap.o
nvidia/nv-dma.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-dma.o] Error 1
  CC [M]  nvidia/nv-p2p.o
  CC [M]  nvidia/nv-pat.o
nvidia/nv-mmap.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-mmap.o] Error 1
nvidia/nv-p2p.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/nv-procfs.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-p2p.o] Error 1
  CC [M]  nvidia/nv-usermap.o
nvidia/nv-pat.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-pat.o] Error 1
  CC [M]  nvidia/nv-vm.o
nvidia/nv-procfs.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
nvidia/nv-usermap.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-procfs.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-usermap.o] Error 1
  CC [M]  nvidia/nv-vtophys.o
nvidia/nv-vm.c:24:10: fatal error: os-interface.h: No such file or directory
   24 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/os-interface.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-vm.o] Error 1
  CC [M]  nvidia/os-mlock.o
nvidia/nv-vtophys.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-vtophys.o] Error 1
nvidia/os-interface.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/os-pci.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/os-interface.o] Error 1
  CC [M]  nvidia/os-registry.o
nvidia/os-mlock.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/os-mlock.o] Error 1
  CC [M]  nvidia/os-usermap.o
nvidia/os-pci.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/os-pci.o] Error 1
nvidia/os-registry.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/nv-modeset-interface.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/os-registry.o] Error 1
nvidia/os-usermap.c:26:10: fatal error: os-interface.h: No such file or directory
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/nv-pci-table.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/os-usermap.o] Error 1
  CC [M]  nvidia/nv-kthread-q.o
nvidia/nv-modeset-interface.c:24:10: fatal error: nv-modeset-interface.h: No such file or directory
   24 | #include "nv-modeset-interface.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-modeset-interface.o] Error 1
  CC [M]  nvidia/nv-memdbg.o
nvidia/nv-kthread-q.c:24:10: fatal error: nv-kthread-q.h: No such file or directory
   24 | #include "nv-kthread-q.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-kthread-q.o] Error 1
  CC [M]  nvidia/nv-ibmnpu.o
nvidia/nv-memdbg.c:24:10: fatal error: nv-memdbg.h: No such file or directory
   24 | #include "nv-memdbg.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-memdbg.o] Error 1
  CC [M]  nvidia/nv-report-err.o
nvidia/nv-ibmnpu.c:27:10: fatal error: nv-linux.h: No such file or directory
   27 | #include "nv-linux.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-ibmnpu.o] Error 1
  CC [M]  nvidia/nv-rsync.o
nvidia/nv-report-err.c:25:10: fatal error: nv-linux.h: No such file or directory
   25 | #include "nv-linux.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-report-err.o] Error 1
  CC [M]  nvidia/nv-msi.o
nvidia/nv-rsync.c:24:10: fatal error: nv-linux.h: No such file or directory
   24 | #include "nv-linux.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-rsync.o] Error 1
  CC [M]  nvidia/nv-caps.o
nvidia/nv-msi.c:24:10: fatal error: nv-msi.h: No such file or directory
   24 | #include "nv-msi.h"
      |          ^~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-msi.o] Error 1
  CC [M]  nvidia/nv-caps-imex.o
nvidia/nv-caps.c:24:10: fatal error: nv-linux.h: No such file or directory
   24 | #include "nv-linux.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-caps.o] Error 1
  CC [M]  nvidia/nv_uvm_interface.o
nvidia/nv-caps-imex.c:24:10: fatal error: nv-linux.h: No such file or directory
   24 | #include "nv-linux.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-caps-imex.o] Error 1
  CC [M]  nvidia/libspdm_aead.o
nvidia/nv_uvm_interface.c:32:10: fatal error: os-interface.h: No such file or directory
   32 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv_uvm_interface.o] Error 1
  CC [M]  nvidia/libspdm_ecc.o
In file included from nvidia/libspdm_aead.c:24:
nvidia/internal_crypt_lib.h:32:10: fatal error: conftest.h: No such file or directory
   32 | #include "conftest.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/libspdm_aead.o] Error 1
  CC [M]  nvidia/libspdm_hkdf.o
nvidia/nv-nano-timer.c:30:10: fatal error: os-interface.h: No such file or directory
   30 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-nano-timer.o] Error 1
  CC [M]  nvidia/libspdm_rand.o
In file included from nvidia/libspdm_hkdf.c:24:
nvidia/internal_crypt_lib.h:32:10: fatal error: conftest.h: No such file or directory
   32 | #include "conftest.h"
      |          ^~~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/libspdm_shash.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/libspdm_hkdf.o] Error 1
  CC [M]  nvidia/libspdm_rsa.o
In file included from nvidia/libspdm_shash.c:24:
nvidia/internal_crypt_lib.h:32:10: fatal error: conftest.h: No such file or directory
   32 | #include "conftest.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/libspdm_shash.o] Error 1
  CC [M]  nvidia/libspdm_aead_aes_gcm.o
  CC [M]  nvidia/libspdm_sha.o
  CC [M]  nvidia/libspdm_hmac_sha.o
  CC [M]  nvidia/libspdm_internal_crypt_lib.o
  CC [M]  nvidia/libspdm_hkdf_sha.o
  CC [M]  nvidia/libspdm_ec.o
  CC [M]  nvidia/libspdm_x509.o
  CC [M]  nvidia/libspdm_rsa_ext.o
  CC [M]  nvidia/nv-vgpu-vfio-interface.o
nvidia/nv-vgpu-vfio-interface.c:24:10: fatal error: nv-linux.h: No such file or directory
   24 | #include "nv-linux.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-vgpu-vfio-interface.o] Error 1
  CC [M]  nvidia/nvlink_linux.o
  CC [M]  nvidia/nvlink_caps.o
  CC [M]  nvidia/linux_nvswitch.o
nvidia/nvlink_linux.c:24:10: fatal error: conftest.h: No such file or directory
   24 | #include "conftest.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nvlink_linux.o] Error 1
In file included from nvidia/nvlink_os.h:31,
                 from nvidia/nvlink_caps.c:24:
nvidia/nvlink_common.h:31:10: fatal error: nvtypes.h: No such file or directory
   31 | #include "nvtypes.h"
      |          ^~~~~~~~~~~
compilation terminated.
  CC [M]  nvidia/procfs_nvswitch.o
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nvlink_caps.o] Error 1
  CC [M]  nvidia/i2c_nvswitch.o
In file included from nvidia/linux_nvswitch.c:24:
nvidia/linux_nvswitch.h:27:10: fatal error: nvmisc.h: No such file or directory
   27 | #include "nvmisc.h"
      |          ^~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/linux_nvswitch.o] Error 1
  CC [M]  nvidia-vgpu-vfio/nvidia-vgpu-vfio.o
In file included from nvidia/procfs_nvswitch.c:24:
nvidia/linux_nvswitch.h:27:10: fatal error: nvmisc.h: No such file or directory
   27 | #include "nvmisc.h"
      |          ^~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/procfs_nvswitch.o] Error 1
In file included from nvidia/i2c_nvswitch.c:24:
nvidia/linux_nvswitch.h:27:10: fatal error: nvmisc.h: No such file or directory
   27 | #include "nvmisc.h"
      |          ^~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/i2c_nvswitch.o] Error 1
  CC [M]  nvidia-vgpu-vfio/vgpu-vfio-mdev.o
  CC [M]  nvidia-vgpu-vfio/vgpu-devices.o
nvidia/nv.c:30:10: fatal error: nv-firmware.h: No such file or directory
   30 | #include "nv-firmware.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv.o] Error 1
  CC [M]  nvidia-vgpu-vfio/vgpu-ctldev.o
nvidia/nv-dmabuf.c:24:10: fatal error: nv-dmabuf.h: No such file or directory
   24 | #include "nv-dmabuf.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-dmabuf.o] Error 1
  CC [M]  nvidia-vgpu-vfio/nv-pci-table.o
nvidia/nv-pci.c:25:10: fatal error: nv-pci-types.h: No such file or directory
   25 | #include "nv-pci-types.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-pci.o] Error 1
  CC [M]  nvidia-vgpu-vfio/vgpu-vfio-pci-core.o
nvidia/nv-i2c.c:28:10: fatal error: os-interface.h: No such file or directory
   28 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-i2c.o] Error 1
nvidia/nv-pci-table.c:28:10: fatal error: cpuopsys.h: No such file or directory
   28 | #include "cpuopsys.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia/nv-pci-table.o] Error 1
nvidia-vgpu-vfio/vgpu-devices.c:27:10: fatal error: nvstatus.h: No such file or directory
   27 | #include "nvstatus.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia-vgpu-vfio/vgpu-devices.o] Error 1
nvidia-vgpu-vfio/vgpu-ctldev.c:27:10: fatal error: nvstatus.h: No such file or directory
   27 | #include "nvstatus.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia-vgpu-vfio/vgpu-ctldev.o] Error 1
nvidia-vgpu-vfio/nv-pci-table.c:28:10: fatal error: cpuopsys.h: No such file or directory
   28 | #include "cpuopsys.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.17.13-1-pve/scripts/Makefile.build:287: nvidia-vgpu-vfio/nv-pci-table.o] Error 1
nvidia-vgpu-vfio/vgpu-vfio-mdev.c:31:10: fatal error: nvstatus.h: No such file or directory
```

**Comment by MyNameIsBorat** [comment]
I am having the same issue with Tesla M60. Did you manage to find the solution?

**Comment by nate-moo** [comment]
Alas no, I've passed it into a debian 12 VM and installed older drivers. Looks like the best option is drop to proxmox 8 and hope for the best. :/

**Comment by MyNameIsBorat** [comment]
That's sad. I would wait for a fix. Would you know if I can just install the drivers manually for vgpu since I have a tesla m60?

**Comment by Dev-Fabry** [comment]
Hi,
Maybe you should try a newer version of the v16 drivers.

We're currently on v16.14 (so v16.9 is a bit old).
So far, no one has shared the v16.13 and v16.14 drivers, but the v16.12 ones are available.
EDIT: Now v16.13 and v16.14 are available

I don't have a Tesla M60, only a Tesla P4 and two Tesla V100s, but I can say that the v16.12 drivers seem to work well, and by applying a small patch to the sources, I can say that they even work on the 6.17 kernel (they still don't work on the very recent 7.0.0 kernel), without forcing you to stick with the 6.14 kernel.

**Comment by MyNameIsBorat** [comment]
I tried with 16.12 Drivers, it didn't work. I set the kernel manually pinned to 6.14. Anyways, I got around to installing official nvidia drivers without vgpu func

**Comment by Dev-Fabry** [comment]
Now there are available also version 16.14 which works with kernel 6.17 and also with kernel 7.0 without patches

**Comment by anomixer** [comment]
Hi everyone 👋

Great news — this is now fixed in the latest update!

A big **thank you to @Dev-Fabry** for investigating 16.12/16.13/16.14, testing them against kernel 6.17 with a source patch, and being the first to confirm that **16.14 works on both kernel 6.17 and 7.0 without any patches** — that information was exactly what we needed to push this fix. 🙌

Also thanks to @nate-moo and @tdtmusic2 for the detailed logs (M60 + T4 on 6.14/6.17) — they really helped narrow down the root cause.

**What changed in this update:**
- ✅ Added driver branches **16.10 → 16.14** to the installer menu
- ✅ **16.14** is now the recommended selection for Pascal or older GPUs — works on kernel 6.14.x, 6.17.x, and 7.0 without extra patches
- ✅ Removed the forced kernel downgrade restriction — no more being pinned to an old kernel

**To fix your setup:**
1. `git pull` in your installer directory
2. Re-run `bash proxmox-installer.sh`
3. Select **16.14** from the Pascal driver list

@MyNameIsBorat — if you're still wanting vGPU working on your M60 on a modern kernel, give 16.14 another shot with the updated script. Should be smooth now.
